---
language: php
php:
  - 7.0
  - 7.1

env:
  - PHP_ENV="desenvolvimento"
  - PHP_ENV="producao";SESSION_SECRET="la li"

addons:
    code_climate:
        repo_token: $CODECLIMATE_API_TOKEN

cache:
  directories:
    - ~/.composer/cache

sudo: false
dist: trusty

services:
  - mangodb

install: composer install

before_script:
  - travis_retry composer self-update
  - composer require codeclimate/php-test-reporter --dev

script:
  - phpunit --configuration phpunit.xml coverage-text
  - gulp travis
  - vendor/bin/phpunit --debug

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
#  - vendor/bin/test-reporter
